// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfQQjYR2eOh_c4nk6-a8SDIEK68nCbC1Y',
    appId: '1:464681843290:web:80dc90dabd67ce93583663',
    messagingSenderId: '464681843290',
    projectId: 'fabric-1320d',
    authDomain: 'fabric-1320d.firebaseapp.com',
    storageBucket: 'fabric-1320d.firebasestorage.app',
    measurementId: 'G-PVZBQM7ZHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdp7HDDKP4kjabeyqTQG0ErOFSK6yLGIM',
    appId: '1:464681843290:android:a9d423dc776b830f583663',
    messagingSenderId: '464681843290',
    projectId: 'fabric-1320d',
    storageBucket: 'fabric-1320d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3iif1cxKhY-q3a_vN5-AzQcsrsJBtIx4',
    appId: '1:464681843290:ios:077bf69f41270100583663',
    messagingSenderId: '464681843290',
    projectId: 'fabric-1320d',
    storageBucket: 'fabric-1320d.firebasestorage.app',
    iosClientId: '464681843290-gs2d06rnh0plsjb1bkf2l8mca1pbsb3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.fabric',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3iif1cxKhY-q3a_vN5-AzQcsrsJBtIx4',
    appId: '1:464681843290:ios:077bf69f41270100583663',
    messagingSenderId: '464681843290',
    projectId: 'fabric-1320d',
    storageBucket: 'fabric-1320d.firebasestorage.app',
    iosClientId: '464681843290-gs2d06rnh0plsjb1bkf2l8mca1pbsb3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.fabric',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfQQjYR2eOh_c4nk6-a8SDIEK68nCbC1Y',
    appId: '1:464681843290:web:6b5271015595ed6e583663',
    messagingSenderId: '464681843290',
    projectId: 'fabric-1320d',
    authDomain: 'fabric-1320d.firebaseapp.com',
    storageBucket: 'fabric-1320d.firebasestorage.app',
    measurementId: 'G-SM20LESHED',
  );
}
